# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storeentryrequest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Applicant'),
        ),
        migrations.AlterField(
            model_name='storeentryrequest',
            name='store_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StoreEntry'),
        ),
    ]
