# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0002_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thresholdclient',
            old_name='client_ip',
            new_name='client_address',
        ),
        migrations.AlterField(
            model_name='thresholdclient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
