# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreEntry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pseudonym', models.CharField(default='a60398f8f8784f3f93f2c7c87d1dc047', editable=False, max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField(editable=False)),
            ],
        ),
    ]
