# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentry',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='storeentry',
            name='pseudonym',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
