# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20171115_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeentry',
            name='last_access',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storeentry',
            name='search_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeentry',
            name='usages',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='storeentry',
            name='pseudonym',
            field=models.CharField(editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
