# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20171121_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentry',
            name='usages',
            field=models.IntegerField(default=0),
        ),
    ]
