# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_partialdecryptionforrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialdecryptionforrequest',
            name='accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
