# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_partialdecryptionforrequest_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialdecryptionforrequest',
            name='partial_decryption',
            field=models.TextField(null=True),
        ),
    ]
