# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20180111_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeentry',
            name='decrypted_content',
            field=models.TextField(null=True),
        ),
    ]
