# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0006_storeclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thresholdclient',
            name='name',
        ),
        migrations.AddField(
            model_name='thresholdclient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
