# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20180214_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdclient',
            name='client_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='thresholdclient',
            name='client_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thresholdclient',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
