# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20180214_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
